baseURL = "https://docs.themefisher.com/"
languageCode = "en-us"
languageName = "En"
theme = "godocs-hugo"
title = "Documentation Website for Themefisher"
enableGitInfo = true
[markup.goldmark.renderer]
unsafe = true
[markup.tableOfContents]
startLevel = 0
endLevel = 6
ordered = false
[[menu.footer]]
name = "Github"
url = "https://github.com/themefisher/"
weight = 2
[[menu.footer]]
name = "Contact"
url = "https://themefisher.com/contact"
weight = 1
[outputs]
home = ["HTML", "JSON"]
[params]
logo = "images/logo.png"
author = "Themefisher"
description = "This is meta description"
topic_title = "Browse Your Topics"
premium_badge = true
edit_page_url = "https://github.com/themefisher/documentation/edit/master/content/"
copyright = "Copyright &copy; 2020 [Themefisher](https://themefisher.com/) Docs build with [Godocs Theme](https://gethugothemes.com/products/godocs-hugo-documentation-theme/)"
[params.banner]
image = "images/banner.jpg"
subtitle = "We are the largest elegant design, well coded bootstrap base theme provider. Our all themes documentation is available here."
title = "Welcome to Themefisher Docs"
[params.call_to_action]
content = "If you don’t find the answer to your issue at our guide and documentation, open a support ticket. Our support team will be with you as soon as possible to solve your problem."
enable = true
image = "images/cta-illustration.jpg"
title = "Still Didn't Find Your Answer?"
[params.call_to_action.button]
enable = "true"
label = "Submit a ticket"
link = "https://themefisher.com/contact"
[params.navigation_button_bordered]
enable = true
label = "submit ticket"
link = "https://themefisher.com/contact"
[params.navigation_button_solid]
enable = true
label = "guide"
link = "guide"
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.css]]
link = "plugins/search/auto-complete.css"
[[params.plugins.css]]
link = "plugins/featherlight/featherlight.min.css"
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/masonry/masonry.min.js"
[[params.plugins.js]]
link = "plugins/featherlight/featherlight.min.js"
[[params.plugins.js]]
link = "plugins/clipboard/clipboard.min.js"
[[params.plugins.js]]
link = "plugins/search/auto-complete.js"
[[params.plugins.js]]
link = "plugins/scrollmenu/scrollmenu.min.js"
[[params.plugins.js]]
link = "plugins/search/search.js"
[[params.plugins.js]]
link = "plugins/search/lunr.min.js"
[[params.plugins.js]]
link = "plugins/search/fuse.min.js"
[[params.plugins.js]]
link = "plugins/search/mark.js"
[[params.plugins.js]]
link = "plugins/search/search-page.js"
[[params.plugins.js]]
link = "plugins/turbolinks/turbolinks.js"
[params.preloader]
enable = true
preloader = ""
[[params.social]]
icon = "ti-facebook"
link = "https://facebook.com/themefisher"
title = "facebook"
[[params.social]]
icon = "ti-twitter-alt"
link = "https://twitter.com/themefisher"
title = "twitter"
[[params.social]]
icon = "ti-github"
link = "https://github.com/themefisher"
title = "github"